# Generated by Django 5.0.6 on 2024-05-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minor1', '0002_carvariety_delete_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='carvariety',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
